doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'sqlsrv'
        server_version: '14.0.3460.9'
        charset: utf-8
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PWD)%'
        dbname: '%env(DATABASE_NAME)%'
        host: 127.0.0.1
        port: 1433

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Test:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Tests/Entity'
                prefix: 'App\Tests\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            host: 127.0.0.1
            port: 1433
            user: 'ioda'
            password: 'g4t3sC4n34tMySh0rtz'
            dbname: 'infonihr'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
