version: '3.8'
services:
  php:
    container_name: ioda_php
    build: # we are specifying the version in the Dockerfile
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./bin:/var/www/html/bin
    working_dir: /var/www/html
    ports:
      - "8000:8000"
