version: '3.8'
services:

  php:
    container_name: ioda_php
    build: # we are specifying the version in the Dockerfile
      context: .
      target: php
      dockerfile: Dockerfile
    volumes:
      - .:/srv/ioda
    working_dir: /srv/ioda
    ports:
      - "8000:8000"

  info_nihr_db:
    container_name: infonihr
    hostname: nihr_dkr
    build:
      context: .
      target: mssql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"