version: '3.8'
services:

  php:
    container_name: ioda_php
    build: # we are specifying the version in the Dockerfile
      context: .
      target: php8
      dockerfile: Dockerfile
    volumes:
      - .:/srv/ioda
    working_dir: /srv/ioda
    ports:
      - "8000:8000"



#@todo ditch me if it didn't break?
#volumes:
#  ioda: