version: '3.8'
services:

  php:
    container_name: ioda_php
    build: # we are specifying the version in the Dockerfile
      context: .
      target: php
      dockerfile: Dockerfile
    volumes:
      - .:/srv/ioda
    working_dir: /srv/ioda
    ports:
      - "8000:8000"

  info_nihr_db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Ff4rtB4gsFTWasl0IH8s3qu3ls3
    container_name: infonihr
    hostname: nihr_dkr
    build:
      context: .
      target: mssql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
      -
#    healthcheck:   # @todo this isn't doing the job yet. We need to wait until the server us running before we run sql
#      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "127.0.0.1", "-U", "sa", "-P", "Ff4rtB4gsFTWasl0IH8s3qu3ls3", "-Q", "SELECT 1", "||", "exit 1" ]
#      interval: 8s
#      timeout: 3s
#      retries: 5
#      start_period: 8s
#
#  initializr:
#    image: mcr.microsoft.com/mssql-tools
##    volumes:
##      - ./tests/assets/mssql/init:/usr/src/sql
#    build:
#      context: .
#    depends_on:
#      info_nihr_db:
#        condition: service_started
#    command:
#      - /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U SA -P 'Ff4rtB4gsFTWasl0IH8s3qu3ls3' -i ./usr/src/sql/setupTestDB.sql


