name: Docker build and test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
    tags:
      - '*'



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: build and run the docker container
        run: |
          docker compose up -d
        shell: bash

      - name: run tests
        run: |
          docker exec ioda_php composer run test
        shell: bash
